#index
home:
    resource: "@PAGEDemoBundle/Controller/homeController.php"
    type:     annotation

#perfiles
_profile:
    resource: "@PAGEDemoBundle/Controller/ProfileController.php"
    type:     annotation

#seguridad
_secured:
    resource: "@PAGEDemoBundle/Controller/SecuredController.php"
    type:     annotation

#load json
_load:
    resource: "@PAGEDemoBundle/Controller/LoadController.php"
    type:     annotation

#Usuarios
_user:
    resource: "@PAGEDemoBundle/Controller/UserController.php"
    type:     annotation

#Cursos
_cursos:
    resource: "@PAGEDemoBundle/Controller/LevelController.php"
    type:     annotation

#Asignaturas
_asignaturas:
    resource: "@PAGEDemoBundle/Controller/SubjectController.php"
    type:     annotation

#profesores
_profesores:
    resource: "@PAGEDemoBundle/Controller/TeacherController.php"
    type:     annotation

#profesoresIn
_profesoresIn:
    resource: "@PAGEDemoBundle/Controller/InTeacherController.php"
    type:     annotation

#Alumnos
_alumnos:
    resource: "@PAGEDemoBundle/Controller/StudentController.php"
    type:     annotation

#AlumnosIn
_alumnosIn:
    resource: "@PAGEDemoBundle/Controller/InStudentController.php"
    type:     annotation

#InAlumnosIn
_inAlumnosIn:
    resource: "@PAGEDemoBundle/Controller/InStudentInController.php"
    type:     annotation

#Apoderados
_apoderados:
    resource: "@PAGEDemoBundle/Controller/AgentController.php"
    type:     annotation

#Prueba
_prueba:
    resource: "@PAGEDemoBundle/Controller/TestController.php"
    type:     annotation

#Documentos
_documentos:
    resource: "@PAGEDemoBundle/Controller/DocumentController.php"
    type:     annotation

#Horario
_horario:
    resource: "@PAGEDemoBundle/Controller/ScheduleController.php"
    type:     annotation

#Notas
_notas:
    resource: "@PAGEDemoBundle/Controller/GradeController.php"
    type:     annotation

#Asistencia
_callroll:
    resource: "@PAGEDemoBundle/Controller/CallRollController.php"
    type:     annotation

#In Asistencia
_incallroll:
    resource: "@PAGEDemoBundle/Controller/InCallRollController.php"
    type:     annotation

#Institucion
_institution:
    resource: "@PAGEDemoBundle/Controller/InstitutionController.php"
    type:     annotation

#In Institucion
_ininstitution:
    resource: "@PAGEDemoBundle/Controller/InInstitutionController.php"
    type:     annotation